---
- name: Copy worker certificates
  copy:
    src: "{{ playbook_dir }}/../../kazan-ssl/pki/{{ item }}"
    dest: "/etc/etcd/"
    owner: root
    group: root
    mode: 0644

  become: true
  with_items:
    - ca/ca.pem
    - clients/w1.kazan.schleppe-key.pem
    - clients/w1.kazan.schleppe.pem
    - clients/w2.kazan.schleppe-key.pem
    - clients/w2.kazan.schleppe.pem
    - clients/w3.kazan.schleppe-key.pem
    - clients/w3.kazan.schleppe.pem