---
- name: "launch"
  hosts: controller
  roles: 
    - role: roles/common
    - role: roles/etcd
    - role: roles/kubernetes

- hosts: worker
  roles:
    - role: roles/common
    - role: roles/etcd